# SECRET VARIABLES:
# AWS_ACCESS_KEY
# AWS_SECRET_KEY

name: CI

on: 
  pull_request:
  push:
    branches:
      - master

env: 
  IMAGE_NAME: "nginx-geolite"
  AWS_REGION: "eu-west-2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clone
      uses: actions/checkout@v1

    - name: Build Docker image
      run: docker build --tag ${{ env.IMAGE_NAME }}:latest .

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        region: ${{ env.AWS_REGION}}
        image: ${{ env.IMAGE_NAME }}

    - name: Deployed successfully!
      run: echo App deployed to ECR
